variables:
  S3_BUCKET_NAME: "3coresec" 
 
stages:
  - build
  - publish
  - deploy
 
build:
  only: [develop]
  image: node:16-alpine3.12
  stage: build
  script:
    - rm -f package-lock.json
    - npm install -g @angular/cli
    - npm install
    - ng build
    - echo "BUILD SUCCESSFUL FOR ADMIN APP"
  artifacts:
    paths:
      - dist/
      - node_modules/
 
publish:
  only: [develop]
  needs: ["build"]
  stage: publish
  image: docker
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin  
  script:
    - docker  build -t $CI_REGISTRY_IMAGE .
    - docker image ls
    - docker push $CI_REGISTRY_IMAGE
 
# deploy: 
#   only: [develop]
#   stage: deploy
#   image: alpine
#   script: 
#     - cp  deploy.sh /home/ubuntu/devops/ | sh deploy.sh


 